---
development:
  cloud_name: pitchfunnel
  api_key: '278218189443232'
  api_secret: vaR7eWETooQMjlSK4ky02bdEOZU
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: pitchfunnel
  api_key: '278218189443232'
  api_secret: vaR7eWETooQMjlSK4ky02bdEOZU
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: pitchfunnel
  api_key: '278218189443232'
  api_secret: vaR7eWETooQMjlSK4ky02bdEOZU
  enhance_image_tag: true
  static_image_support: false
