---
development:
  cloud_name: dpxcevibg
  api_key: '924486791994526'
  api_secret: sps2uu6ZxtjOXeLi8kZ1nAMVS80
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dpxcevibg
  api_key: '924486791994526'
  api_secret: sps2uu6ZxtjOXeLi8kZ1nAMVS80
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dpxcevibg
  api_key: '924486791994526'
  api_secret: sps2uu6ZxtjOXeLi8kZ1nAMVS80
  enhance_image_tag: true
  static_image_support: false